/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ReferencesRouteImport } from './routes/references'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as EditorProjectIdRouteImport } from './routes/editor.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesRoute = ReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorProjectIdRoute = EditorProjectIdRouteImport.update({
  id: '/editor/$projectId',
  path: '/editor/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/brand': typeof BrandRoute
  '/create': typeof CreateRoute
  '/projects': typeof ProjectsRoute
  '/references': typeof ReferencesRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/editor/$projectId': typeof EditorProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/brand': typeof BrandRoute
  '/create': typeof CreateRoute
  '/projects': typeof ProjectsRoute
  '/references': typeof ReferencesRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/editor/$projectId': typeof EditorProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/brand': typeof BrandRoute
  '/create': typeof CreateRoute
  '/projects': typeof ProjectsRoute
  '/references': typeof ReferencesRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/editor/$projectId': typeof EditorProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/brand'
    | '/create'
    | '/projects'
    | '/references'
    | '/settings'
    | '/templates'
    | '/editor/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/brand'
    | '/create'
    | '/projects'
    | '/references'
    | '/settings'
    | '/templates'
    | '/editor/$projectId'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/brand'
    | '/create'
    | '/projects'
    | '/references'
    | '/settings'
    | '/templates'
    | '/editor/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  BrandRoute: typeof BrandRoute
  CreateRoute: typeof CreateRoute
  ProjectsRoute: typeof ProjectsRoute
  ReferencesRoute: typeof ReferencesRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  EditorProjectIdRoute: typeof EditorProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references': {
      id: '/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof ReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$projectId': {
      id: '/editor/$projectId'
      path: '/editor/$projectId'
      fullPath: '/editor/$projectId'
      preLoaderRoute: typeof EditorProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  BrandRoute: BrandRoute,
  CreateRoute: CreateRoute,
  ProjectsRoute: ProjectsRoute,
  ReferencesRoute: ReferencesRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  EditorProjectIdRoute: EditorProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
